### ISSUE TITLE
Differences to vagrant-reload plugin?

### ISSUE THREAD

**Issue by krlmlr** [exratione/vagrant-provision-reboot#4]
Are you aware of the [`vagrant-reload` plugin](https://github.com/aidanns/vagrant-reload)? It is installable via `vagrant plugin install` and seems to do the same thing as this plugin. However, I'm not familiar with the details -- is it really the same, or are there subtle differences?

**Comment by exratione** [comment]
I haven't tried it. It is a different approach that is less hacky than this one and therefore should be better and more resilient to future changes. It uses the defined reload behavior and allows it to be called in the provisioning process, which should handle the problem remapping of synced folders automatically.

**Comment by krlmlr** [comment]
Thanks, this was very helpful. The `vagrant-reload` plugin works well for my use case.
