### ISSUE TITLE
Doesn't work with AWS provider

### ISSUE THREAD

**Issue by lmilbaum** [exratione/vagrant-provision-reboot#5]
Same issue as with Parallels provider.
Tried to add the next code to vagrant-provision-reboot-plugin.rb

module VagrantPlugins
  module AWS
    module Action
      def self.action_remount_synced_folders
      end
    end
  end
end

It didn't work. I am a newbie in Ruby/Vagrant.

**Comment by exratione** [comment]
Try https://github.com/aidanns/vagrant-reload instead. It's a generally better alternative.

**Comment by lmilbaum** [comment]
Thanks for the suggestion. It worked perfectly.
